<?php
if (function_exists('acf_add_local_field_group')):
    acf_add_local_field_group([
        'key'                   => 'theme_setting_group',
        'title'                 => 'تنظیمات قالب',
        'fields'                => [
            [
                'key'               => 'header_group',
                'label'             => 'تنظیمات سربرگ',
                'name'              => 'header_options',
                'type'              => 'group',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'layout'            => 'row',
                'sub_fields'        => [
                    [
                        'key'               => 'major_button_field',
                        'label'             => 'دکمه خرید عمده',
                        'name'              => 'major_buy_link',
                        'type'              => 'link',
                        'instructions'      => 'لینک برگه خرید عمده (لینک را وارد کنید یا برگه آنرا انتخاب کنید)',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'array',
                    ],
                ],
            ],
        ],
        'location'              => [
            [
                [
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'theme-general-settings',
                ],
            ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ]);
    acf_add_local_field_group([
        'key'                   => 'front_page_options',
        'title'                 => 'تنظیمات صفحه اصلی',
        'fields'                => [
            [
                'key'               => 'top_small_image',
                'label'             => 'تصویر کوچک (سمت راست)',
                'name'              => 'small_image',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '400',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'small_image_link_field',
                'label'             => 'لینک تصویر کوچک',
                'name'              => 'small_image_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'top_big_image',
                'label'             => 'تصویر بزرگ (سمت چپ)',
                'name'              => 'big_image',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '800',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'big_image_link_field',
                'label'             => 'لینک تصویر بزرگ',
                'name'              => 'big_image_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید تصویر به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'bottom_image_1_field',
                'label'             => 'تصویر ۱ (از راست به چپ)',
                'name'              => 'bottom_image_1',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '200',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'image_1_link_field',
                'label'             => 'لینک تصویر ۱',
                'name'              => 'image_1_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'bottom_image_2_field',
                'label'             => 'تصویر ۲ (از راست به چپ)',
                'name'              => 'bottom_image_2',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '200',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'image_2_link_field',
                'label'             => 'لینک تصویر ۲',
                'name'              => 'image_2_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'bottom_image_3_field',
                'label'             => 'تصویر ۳ (از راست به چپ)',
                'name'              => 'bottom_image_3',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '200',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'image_3_link_field',
                'label'             => 'لینک تصویر ۳',
                'name'              => 'image_3_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'bottom_image_4_field',
                'label'             => 'تصویر ۴ (از راست به چپ)',
                'name'              => 'bottom_image_4',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '200',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'image_4_link_field',
                'label'             => 'لینک تصویر ۴',
                'name'              => 'image_4_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'frontpage_sales_categories_field',
                'label'             => 'دسته بندی های پرفروش',
                'name'              => 'frontpage_sales_categories',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'choices'           => [],
                'default_value'     => [
                ],
                'allow_null'        => 0,
                'multiple'          => 1,
                'ui'                => 1,
                'ajax'              => 0,
                'return_format'     => 'array',
                'placeholder'       => '',
            ],
            [
                'key'               => 'best_sellers_button_link_field',
                'label'             => 'لینک دکمه همه پرفروشترین ها',
                'name'              => 'best_sellers_button_link',
                'type'              => 'link',
                'instructions'      => 'لینک دکمه همه محصولات را ببینید در قسمت پرفروشترین ها',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'latest_product_categories_field',
                'label'             => 'دسته بندی های جدیدترین ها',
                'name'              => 'latest_product_categories',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'choices'           => [],
                'default_value'     => [
                ],
                'allow_null'        => 0,
                'multiple'          => 1,
                'ui'                => 1,
                'ajax'              => 0,
                'return_format'     => 'array',
                'placeholder'       => '',
            ],
            [
                'key'               => 'latest_button_link_field',
                'label'             => 'لینک دکمه همه جدیدترین ها',
                'name'              => 'latest_button_link',
                'type'              => 'link',
                'instructions'      => 'لینک دکمه همه محصولات را ببینید در قسمت جدیدترین ها',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
        ],
        'location'              => [
            [
                [
                    'param'    => 'page',
                    'operator' => '==',
                    'value'    => get_option('page_on_front'),
                ],
            ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ]);

//	acf_add_local_field_group(array(
//		'key' => 'group_6150e9bd58068',
//		'title' => 'گزینه های برگه دسته بندی',
//		'fields' => array(
//			array(
//				'key' => 'field_6150e9dadcdc4',
//				'label' => 'محتوای باکس توضیحات',
//				'name' => 'about-top-text',
//				'type' => 'wysiwyg',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'tabs' => 'all',
//				'toolbar' => 'full',
//				'media_upload' => 1,
//				'delay' => 0,
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'page_template',
//					'operator' => '==',
//					'value' => 'template-category.php',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_6130b55a1163e',
//		'title' => 'گزینه های دسته بندی',
//		'fields' => array(
//			array(
//				'key' => 'field_6130b5833e635',
//				'label' => 'عنوان درباره(جستجو)',
//				'name' => 'about-title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 1,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'taxonomy',
//					'operator' => '==',
//					'value' => 'category',
//				),
//			),
//			array(
//				array(
//					'param' => 'taxonomy',
//					'operator' => '==',
//					'value' => 'post_tag',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_61290da32f316',
//		'title' => 'گزینه های صفحه اصلی',
//		'fields' => array(
//			array(
//				'key' => 'field_61290dba64fc5',
//				'label' => 'تصاویر بالای صفحه',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_61290e0364fc6',
//				'label' => 'تصویر بزرگ (سمت چپ)',
//				'name' => 'big_image',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'id',
//				'preview_size' => 'thumbnail',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//			array(
//				'key' => 'field_61290e5964fc7',
//				'label' => 'تصویر کوچک(سمت راست)',
//				'name' => 'small_image',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'id',
//				'preview_size' => 'thumbnail',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//			array(
//				'key' => 'field_612934e26ff0b',
//				'label' => 'شبکه های اجتماعی',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_61293a1eae9c0',
//				'label' => 'عنوان مطالب بیشتر',
//				'name' => 'view_more_post_title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_61293a3dae9c1',
//				'label' => 'عنوان شبکه اجتماعی',
//				'name' => 'social_network_title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_612934fd6ff0c',
//				'label' => 'شبکه اجتماعی',
//				'name' => 'social_network',
//				'type' => 'repeater',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'collapsed' => '',
//				'min' => 0,
//				'max' => 0,
//				'layout' => 'table',
//				'button_label' => 'لینک جدید',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_6129365e05016',
//						'label' => 'لینک',
//						'name' => 'link',
//						'type' => 'url',
//						'instructions' => '',
//						'required' => 1,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '40',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//					),
//					array(
//						'key' => 'field_6129369005017',
//						'label' => 'آیکن',
//						'name' => 'icon',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 1,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '40',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => 'icon-instagram',
//						'placeholder' => 'Ex: icon-instagram',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_61293b66a2a7f',
//				'label' => 'دسترسی سریع',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_61293b7aa2a80',
//				'label' => 'عنوان دسترسی سریع',
//				'name' => 'quick_access_title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_61293b89a2a81',
//				'label' => 'دسترسی سریع',
//				'name' => 'quick_access_item',
//				'type' => 'repeater',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'collapsed' => '',
//				'min' => 1,
//				'max' => 5,
//				'layout' => 'table',
//				'button_label' => 'دسترسی جدید',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_61293e1bf40f8',
//						'label' => 'عنوان لینک دسترسی سریع',
//						'name' => 'title',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '40',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_61293bb1a2a82',
//						'label' => 'لینک دسترسی سریع',
//						'name' => 'link',
//						'type' => 'link',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '40',
//							'class' => '',
//							'id' => '',
//						),
//						'return_format' => 'url',
//					),
//					array(
//						'key' => 'field_61293bcea2a83',
//						'label' => 'آیکن دسترسی سریع',
//						'name' => 'icon',
//						'type' => 'select',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '40',
//							'class' => '',
//							'id' => '',
//						),
//						'choices' => array(
//							'support_icon' => 'Support Icon',
//						),
//						'default_value' => 'support_icon',
//						'allow_null' => 0,
//						'multiple' => 0,
//						'ui' => 0,
//						'return_format' => 'value',
//						'ajax' => 0,
//						'placeholder' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_61293eca77330',
//				'label' => 'درباره ما',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_61293eda77331',
//				'label' => 'عنوان اصلی',
//				'name' => 'about_title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_61293f0d77332',
//				'label' => 'پاراگراف',
//				'name' => 'about_paragraph',
//				'type' => 'textarea',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => 6,
//				'new_lines' => '',
//			),
//			array(
//				'key' => 'field_61293f4f77333',
//				'label' => 'دکمه زیرین درباره ما',
//				'name' => 'about_links',
//				'type' => 'repeater',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'collapsed' => '',
//				'min' => 0,
//				'max' => 0,
//				'layout' => 'table',
//				'button_label' => '',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_61293f6877334',
//						'label' => 'متن دکمه',
//						'name' => 'text',
//						'type' => 'text',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '40',
//							'class' => '',
//							'id' => '',
//						),
//						'default_value' => '',
//						'placeholder' => '',
//						'prepend' => '',
//						'append' => '',
//						'maxlength' => '',
//					),
//					array(
//						'key' => 'field_61293f7377335',
//						'label' => 'لینک',
//						'name' => 'link',
//						'type' => 'link',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '40',
//							'class' => '',
//							'id' => '',
//						),
//						'return_format' => 'url',
//					),
//				),
//			),
//			array(
//				'key' => 'field_61294139e2651',
//				'label' => 'کارنامه ها',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_61294149e2652',
//				'label' => 'عنوان بخش کارنامه ها',
//				'name' => 'transcripts_title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_61294176e2653',
//				'label' => 'زیر عنوان بخش کارنامه ها',
//				'name' => 'transcripts_subtitle',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_6129419ae2654',
//				'label' => 'لینک آرشیو کارنامه ها',
//				'name' => 'transcripts_archive_link',
//				'type' => 'link',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'array',
//			),
//			array(
//				'key' => 'field_612941b2e2655',
//				'label' => 'عنوان لینک آرشیو',
//				'name' => 'transcripts_archive_link_title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_61294c8b5a5a9',
//				'label' => 'مقالات',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_61294c965a5aa',
//				'label' => 'عنوان بخش مقالات',
//				'name' => 'articles_title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_61294ca65a5ab',
//				'label' => 'زیرعنوان بخش مقالات',
//				'name' => 'articles_subtitle',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_61294cbc5a5ac',
//				'label' => 'عنوان لینک آرشیو',
//				'name' => 'articles_archive_title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'page_type',
//					'operator' => '==',
//					'value' => 'front_page',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'acf_after_title',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => array(
//			0 => 'the_content',
//		),
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_613e4b468d20b',
//		'title' => 'گزینه های صفحه تماس',
//		'fields' => array(
//			array(
//				'key' => 'field_613fb7813dcc3',
//				'label' => 'فرم تماس و بالای صفحه',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_613e5ab3922a6',
//				'label' => 'محتوای بالای صفحه',
//				'name' => 'contact-top-text',
//				'type' => 'wysiwyg',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'tabs' => 'all',
//				'toolbar' => 'basic',
//				'media_upload' => 0,
//				'delay' => 0,
//			),
//			array(
//				'key' => 'field_613e6782aa20c',
//				'label' => 'عنوان فرم تماس',
//				'name' => 'contact-form-title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => 'عنوان فرم تماس',
//				'placeholder' => 'عنوان فرم تماس',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_613e67baaa20d',
//				'label' => 'زیر عنوان فرم تماس',
//				'name' => 'contact-form-subtitle',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => 'زیر عنوان فرم تماس',
//				'placeholder' => 'عنوان فرم تماس',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_613e5b740b319',
//				'label' => 'کد کوتاه فرم تماس',
//				'name' => 'contact-form-shortcode',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'center_lat' => 35.6966194,
//				'center_lng' => 51.3892365,
//				'zoom' => 12,
//				'key' => 'field_613e4b4ee863b',
//				'label' => 'نقشه',
//				'name' => 'map-location',
//				'type' => 'open_street_map',
//				'instructions' => 'نقشه برای نمایش در کنار فرم تماس',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'leaflet',
//				'layers' => array(
//					0 => 'OpenStreetMap.Mapnik',
//				),
//				'allow_map_layers' => 0,
//				'height' => 480,
//				'max_markers' => 1,
//			),
//			array(
//				'key' => 'field_613fb6f93dcc2',
//				'label' => 'بخش تماس با ما (آدرس و تلفن)',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_613fb8029253c',
//				'label' => 'شماره های تلفن',
//				'name' => 'phone-numbers',
//				'type' => 'repeater',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'collapsed' => 'field_613fb8e59253d',
//				'min' => 0,
//				'max' => 0,
//				'layout' => 'table',
//				'button_label' => 'تلفن جدید',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_613fb8e59253d',
//						'label' => 'شماره تلفن',
//						'name' => 'phone-number',
//						'type' => 'link',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'return_format' => 'array',
//					),
//					array(
//						'key' => 'field_614102b2d9f1c',
//						'label' => 'آیکن',
//						'name' => 'icon',
//						'type' => 'select',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'choices' => array(
//							'instagram' => 'instagram',
//							'dribbble' => 'dribbble',
//							'instagram-o' => 'instagram-o',
//							'facebook' => 'facebook',
//							'github' => 'github',
//							'messenger' => 'messenger',
//							'skype' => 'skype',
//							'telegram' => 'telegram',
//							'twitter' => 'twitter',
//							'whatsapp' => 'whatsapp',
//							'wordpress' => 'wordpress',
//							'call' => 'call',
//							'phone-call' => 'phone-call',
//						),
//						'default_value' => false,
//						'allow_null' => 0,
//						'multiple' => 0,
//						'ui' => 0,
//						'return_format' => 'value',
//						'ajax' => 0,
//						'placeholder' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_613fb9249253e',
//				'label' => 'آدرس',
//				'name' => 'address',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_613fb9459253f',
//				'label' => 'عنوان شبکه اجتماعی',
//				'name' => 'social-links-title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_613fb95f92540',
//				'label' => 'شبکه های اجتماعی',
//				'name' => 'social-links',
//				'type' => 'repeater',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'collapsed' => 'field_613fb8e59253d',
//				'min' => 0,
//				'max' => 0,
//				'layout' => 'table',
//				'button_label' => 'تلفن جدید',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_613fb95f92541',
//						'label' => 'لینک',
//						'name' => 'link',
//						'type' => 'link',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'return_format' => 'url',
//					),
//					array(
//						'key' => 'field_613fb9ae92542',
//						'label' => 'آیکن',
//						'name' => 'icon',
//						'type' => 'select',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'choices' => array(
//							'instagram' => 'instagram',
//							'dribbble' => 'dribbble',
//							'instagram-o' => 'instagram-o',
//							'facebook' => 'facebook',
//							'github' => 'github',
//							'messenger' => 'messenger',
//							'skype' => 'skype',
//							'telegram' => 'telegram',
//							'twitter' => 'twitter',
//							'whatsapp' => 'whatsapp',
//							'wordpress' => 'wordpress',
//							'call' => 'call',
//							'phone-call' => 'phone-call',
//						),
//						'default_value' => 'instagram-o',
//						'allow_null' => 0,
//						'multiple' => 0,
//						'ui' => 1,
//						'ajax' => 0,
//						'return_format' => 'value',
//						'placeholder' => '',
//					),
//				),
//			),
//			array(
//				'key' => 'field_613fbb3354ed2',
//				'label' => 'بخش درباره ما',
//				'name' => '',
//				'type' => 'tab',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'placement' => 'top',
//				'endpoint' => 0,
//			),
//			array(
//				'key' => 'field_613fbb6d54ed3',
//				'label' => 'عنوان',
//				'name' => 'about-title',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_613fbb9d54ed4',
//				'label' => 'متن درباره ما',
//				'name' => 'about-text',
//				'type' => 'wysiwyg',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'tabs' => 'all',
//				'toolbar' => 'full',
//				'media_upload' => 1,
//				'delay' => 0,
//			),
//			array(
//				'key' => 'field_613fbbb354ed5',
//				'label' => 'لینک ادامه درباره',
//				'name' => 'about-link',
//				'type' => 'link',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'array',
//			),
//			array(
//				'key' => 'field_613fbbd054ed6',
//				'label' => 'لینک کارنامه ها',
//				'name' => 'transcripts-link',
//				'type' => 'link',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'array',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'page_template',
//					'operator' => '==',
//					'value' => 'template-about.php',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_612948e8f3865',
//		'title' => 'گزینه های کارنامه',
//		'fields' => array(
//			array(
//				'key' => 'field_612948f24d2ff',
//				'label' => 'نام دانش آموز',
//				'name' => 'student_name',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 1,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//			array(
//				'key' => 'field_612949024d300',
//				'label' => 'رتبه و رشته',
//				'name' => 'student_rank',
//				'type' => 'text',
//				'instructions' => '',
//				'required' => 1,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => '',
//				'maxlength' => '',
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'transcript',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));
//
//	acf_add_local_field_group(array(
//		'key' => 'group_613232a07bdc8',
//		'title' => 'گزینه های نوشته',
//		'fields' => array(
//			array(
//				'key' => 'field_613232aa8dfcc',
//				'label' => 'متن اولیه (intro)',
//				'name' => 'intro_text',
//				'type' => 'textarea',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'maxlength' => '',
//				'rows' => '',
//				'new_lines' => '',
//			),
//			array(
//				'key' => 'field_613232d88dbe4',
//				'label' => 'لینک باکس',
//				'name' => 'links',
//				'type' => 'repeater',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array(
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'collapsed' => 'field_613233208dbe5',
//				'min' => 0,
//				'max' => 0,
//				'layout' => 'table',
//				'button_label' => 'لینک جدید',
//				'sub_fields' => array(
//					array(
//						'key' => 'field_613233208dbe5',
//						'label' => 'link',
//						'name' => 'link-item',
//						'type' => 'link',
//						'instructions' => '',
//						'required' => 0,
//						'conditional_logic' => 0,
//						'wrapper' => array(
//							'width' => '',
//							'class' => '',
//							'id' => '',
//						),
//						'return_format' => 'array',
//					),
//				),
//			),
//		),
//		'location' => array(
//			array(
//				array(
//					'param' => 'post_type',
//					'operator' => '==',
//					'value' => 'post',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => true,
//		'description' => '',
//	));

endif;

add_filter('acf/load_field/name=frontpage_sales_categories', function ($field) {

    // Get all taxonomy terms
    $article_types = get_terms(array(
        'taxonomy'   => 'product_cat',
        'hide_empty' => false
    ));

    // Add each term to the choices array.
    // Example: $field['choices']['review'] = Review
    foreach ($article_types as $type) {
        $field['choices'][$type->term_id] = $type->name;
    }

    return $field;
});