<?php
if (function_exists('acf_add_local_field_group')):
    acf_add_local_field_group([
        'key'                   => 'theme_header_setting_group',
        'title'                 => 'تنظیمات سربرگ',
        'fields'                => [
            [
                'key'               => 'header_group',
                'label'             => 'تنظیمات سربرگ',
                'name'              => 'header_options',
                'type'              => 'group',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'layout'            => 'row',
                'sub_fields'        => [
                    [
                        'key'               => 'major_button_field',
                        'label'             => 'دکمه خرید عمده',
                        'name'              => 'major_buy_link',
                        'type'              => 'link',
                        'instructions'      => 'لینک برگه خرید عمده (لینک را وارد کنید یا برگه آنرا انتخاب کنید)',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'array',
                    ],
                ],
            ],
        ],
        'location'              => [
            [
                [
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'theme-general-settings',
                ],
            ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ]);
    acf_add_local_field_group([
        'key'                   => 'theme_footer_group_settings',
        'title'                 => 'تنظیمات فوتر',
        'fields'                => [
            [
                'key'               => 'about_text_field',
                'label'             => 'درباره ما',
                'name'              => 'about_text',
                'type'              => 'textarea',
                'instructions'      => 'متن درباره ما در فوتر سایت',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               => 'social_title_field',
                'label'             => 'عنوان شبکه اجتماعی',
                'name'              => 'social_title',
                'type'              => 'text',
                'instructions'      => 'عنوان شبکه های اجتماعی در فوتر سایت',
                'required'          => 1,
                'default_value'     => 'ما را در شبکه اجتماعی همراهی کنید',
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],

            [
                'key'               => 'footer_social_links_field',
                'label'             => 'شبکه های اجتماعی',
                'name'              => 'footer_social_links',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'collapsed'         => 'icon',
                'min'               => 0,
                'max'               => 6,
                'layout'            => 'table',
                'button_label'      => 'شبکه اجتماعی جدید',
                'sub_fields'        => [
                    [
                        'key'               => 'social_link',
                        'label'             => 'لینک شبکه اجتماعی',
                        'name'              => 'social_link',
                        'type'              => 'link',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50%',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'array',
                    ],
                    [
                        'key'               => 'social_icon',
                        'label'             => 'آیکن',
                        'name'              => 'social_icon',
                        'type'              => 'select',
                        'instructions'      => '',
                        'required'          => 1,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ],
                        'choices'           => [
                            'telegram'  => 'تلگرام',
                            'twitter'   => 'توییتر',
                            'whatsapp'  => 'واتساپ',
                            'instagram' => 'اینستاگرم'
                        ],
                        'default_value'     => [
                        ],
                        'allow_null'        => 0,
                        'multiple'          => 0,
                        'ui'                => 1,
                        'ajax'              => 0,
                    ]
                ],
            ],

            [
                'key'               => 'footer_contact_title_field',
                'label'             => 'عنوان بخش تماس',
                'name'              => 'footer_contact_title',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'default_value'     => 'با ما تماس بگیرید',
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],

            [
                'key'               => 'footer_phone_field',
                'label'             => 'تلفن فوتر',
                'name'              => 'footer_phone',
                'type'              => 'text',
                'instructions'      => 'شماره های تماس در فوتر سایت',
                'required'          => 0,
                'default_value'     => '',
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],
            [
                'key'               => 'footer_email_field',
                'label'             => 'ایمیل فوتر',
                'name'              => 'footer_email',
                'type'              => 'text',
                'instructions'      => 'آدرس ایمیل در فوتر سایت',
                'required'          => 0,
                'default_value'     => get_bloginfo('admin_email'),
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],

            [
                'key'               => 'namad_title_field',
                'label'             => 'عنوان نمادها',
                'name'              => 'namad_title',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'default_value'     => 'نمادهای الکترونیک',
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
            ],

            [
                'key'               => 'footer_logo_scripts_field',
                'label'             => 'اسکریپت نمادهای الکترونیک',
                'name'              => 'footer_logo_scripts',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'collapsed'         => 'icon',
                'min'               => 0,
                'max'               => 3,
                'layout'            => 'table',
                'button_label'      => 'نماد جدید',
                'sub_fields'        => [
                    [
                        'key'               => 'script',
                        'label'             => 'اسکریپت',
                        'name'              => 'script',
                        'type'              => 'textarea',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '30%',
                            'class' => '',
                            'id'    => '',
                        ],
                    ],
                ],
            ],
        ],
        'location'              => [
            [
                [
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'theme-general-settings',
                ],
            ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ]);

    acf_add_local_field_group([
        'key'    => 'shop_page_options',
        'title'  => 'تنظیمات صفحه فروشگاه',
        'fields' => [
            [
                'key'               => 'top_small_image',
                'label'             => 'تصویر کوچک (سمت راست)',
                'name'              => 'small_image',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '400',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'small_image_link_field',
                'label'             => 'لینک تصویر کوچک',
                'name'              => 'small_image_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'top_big_image',
                'label'             => 'تصویر بزرگ (سمت چپ)',
                'name'              => 'big_image',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '800',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'big_image_link_field',
                'label'             => 'لینک تصویر بزرگ',
                'name'              => 'big_image_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید تصویر به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
        ],
        'location'              => [
            [
                [
                    'param'    => 'page',
                    'operator' => '==',
//                    'value'    => get_option('woocommerce_shop_page_id'),
                    'value'    => 0,
                ],
            ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ]);

    acf_add_local_field_group([
        'key'    => 'front_page_options',
        'title'  => 'تنظیمات صفحه اصلی',
        'fields' => [
            [
                'key'               => 'top_small_image',
                'label'             => 'تصویر کوچک (سمت راست)',
                'name'              => 'small_image',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '400',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'small_image_link_field',
                'label'             => 'لینک تصویر کوچک',
                'name'              => 'small_image_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'top_big_image',
                'label'             => 'تصویر بزرگ (سمت چپ)',
                'name'              => 'big_image',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '800',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'big_image_link_field',
                'label'             => 'لینک تصویر بزرگ',
                'name'              => 'big_image_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید تصویر به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'bottom_image_1_field',
                'label'             => 'تصویر ۱ (از راست به چپ)',
                'name'              => 'bottom_image_1',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '200',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'image_1_link_field',
                'label'             => 'لینک تصویر ۱',
                'name'              => 'image_1_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'bottom_image_2_field',
                'label'             => 'تصویر ۲ (از راست به چپ)',
                'name'              => 'bottom_image_2',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '200',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'image_2_link_field',
                'label'             => 'لینک تصویر ۲',
                'name'              => 'image_2_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'bottom_image_3_field',
                'label'             => 'تصویر ۳ (از راست به چپ)',
                'name'              => 'bottom_image_3',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '200',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'image_3_link_field',
                'label'             => 'لینک تصویر ۳',
                'name'              => 'image_3_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'bottom_image_4_field',
                'label'             => 'تصویر ۴ (از راست به چپ)',
                'name'              => 'bottom_image_4',
                'type'              => 'image',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'id',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '200',
                'min_height'        => '100',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ],
            [
                'key'               => 'image_4_link_field',
                'label'             => 'لینک تصویر ۴',
                'name'              => 'image_4_link',
                'type'              => 'link',
                'instructions'      => 'لینک صفحه ای که میخواهید عکس به آن وصل شود',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'frontpage_sales_categories_field',
                'label'             => 'دسته بندی های پرفروش',
                'name'              => 'frontpage_sales_categories',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'choices'           => [],
                'default_value'     => [
                ],
                'allow_null'        => 0,
                'multiple'          => 1,
                'ui'                => 1,
                'ajax'              => 0,
                'return_format'     => 'array',
                'placeholder'       => '',
            ],
            [
                'key'               => 'best_sellers_button_link_field',
                'label'             => 'لینک دکمه همه پرفروشترین ها',
                'name'              => 'best_sellers_button_link',
                'type'              => 'link',
                'instructions'      => 'لینک دکمه همه محصولات را ببینید در قسمت پرفروشترین ها',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],
            [
                'key'               => 'latest_product_categories_field',
                'label'             => 'دسته بندی های جدیدترین ها',
                'name'              => 'latest_product_categories',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'choices'           => [],
                'default_value'     => [
                ],
                'allow_null'        => 0,
                'multiple'          => 1,
                'ui'                => 1,
                'ajax'              => 0,
                'return_format'     => 'array',
                'placeholder'       => '',
            ],
            [
                'key'               => 'latest_button_link_field',
                'label'             => 'لینک دکمه همه جدیدترین ها',
                'name'              => 'latest_button_link',
                'type'              => 'link',
                'instructions'      => 'لینک دکمه همه محصولات را ببینید در قسمت جدیدترین ها',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],

            [
                'key'               => 'frontpage_have_discount_categories_field',
                'label'             => 'دسته بندی های محصولات تخفیف دار',
                'name'              => 'frontpage_have_discount_categories',
                'type'              => 'select',
                'instructions'      => '',
                'required'          => 1,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'choices'           => [],
                'default_value'     => [
                ],
                'allow_null'        => 0,
                'multiple'          => 1,
                'ui'                => 1,
                'ajax'              => 0,
                'return_format'     => 'array',
                'placeholder'       => '',
            ],
            [
                'key'               => 'have_discount_button_link_field',
                'label'             => 'لینک دکمه آرشیو محصولات تخفیف دار',
                'name'              => 'have_discount_button_link',
                'type'              => 'link',
                'instructions'      => 'لینک دکمه همه محصولات را ببینید در قسمت محصولات تخفیف دار',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '50',
                    'class' => '',
                    'id'    => '',
                ],
                'return_format'     => 'array',
            ],

            [
                'key'               => 'frontpage_brands_field',
                'label'             => 'برندها',
                'name'              => 'frontpage_brands',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'collapsed'         => 'brand',
                'min'               => 0,
                'max'               => 6,
                'layout'            => 'table',
                'button_label'      => 'برند جدید',
                'sub_fields'        => [
                    [
                        'key'               => 'link_field',
                        'label'             => 'لینک برند',
                        'name'              => 'link',
                        'type'              => 'link',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50%',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'array',
                    ],
                    [
                        'key'               => 'brand_field',
                        'label'             => 'برند',
                        'name'              => 'brand',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50%',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'id',
                        'preview_size'      => 'thumbnail',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => ''
                    ]
                ],
            ],

            [
                'key'               => 'frontpage_bottom_advertises_field',
                'label'             => 'تبلیغات پایین صفحه',
                'name'              => 'frontpage_bottom_advertises',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'collapsed'         => 'image',
                'min'               => 0,
                'max'               => 3,
                'layout'            => 'table',
                'button_label'      => 'تبلیغ جدید',
                'sub_fields'        => [
                    [
                        'key'               => 'link_field',
                        'label'             => 'لینک تبلیغ',
                        'name'              => 'link',
                        'type'              => 'link',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50%',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'array',
                    ],
                    [
                        'key'               => 'image_field',
                        'label'             => 'تصویر',
                        'name'              => 'image',
                        'type'              => 'image',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50%',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'id',
                        'preview_size'      => 'thumbnail',
                        'library'           => 'all',
                        'min_width'         => '',
                        'min_height'        => '',
                        'min_size'          => '',
                        'max_width'         => '',
                        'max_height'        => '',
                        'max_size'          => '',
                        'mime_types'        => ''
                    ]
                ],
            ],
            [
                'key'               => 'frontpage_bottom_buttons_field',
                'label'             => 'دکمه های زیر تبلیغات پایین',
                'name'              => 'frontpage_bottom_buttons',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => [
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ],
                'collapsed'         => 'link',
                'min'               => 0,
                'max'               => 6,
                'layout'            => 'block',
                'button_label'      => 'دکمه جدید',
                'sub_fields'        => [
                    [
                        'key'               => 'link_field',
                        'label'             => 'لینک',
                        'name'              => 'link',
                        'type'              => 'link',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => [
                            'width' => '50%',
                            'class' => '',
                            'id'    => '',
                        ],
                        'return_format'     => 'array',
                    ],
                ],
            ],
        ],

        'location'              => [
            [
                [
                    'param'    => 'page',
                    'operator' => '==',
                    'value'    => get_option('page_on_front'),
                ],
            ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => true,
        'description'           => '',
    ]);

    acf_add_local_field_group(array(
        'key' => 'group_6287f5a3bfa13',
        'title' => 'گزینه های صفحه فروشگاه',
        'fields' => array(
            array(
                'key' => 'top_small_image_field',
                'label' => 'تصویر کوچک (سمت راست)',
                'name' => 'top_small_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'small_image_link_field',
                'label' => 'لینک تصویر کوچک',
                'name' => 'small_image_link',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'top_big_image_field',
                'label' => 'تصویر بزرگ(سمت چپ)',
                'name' => 'top_big_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'big_image_link_field',
                'label' => 'لینک تصویر بزرگ',
                'name' => 'big_image_link',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
            array(
                'key' => 'top_categories_list_field',
                'label' => 'دسته بندی های بالا',
                'name' => 'top_categories_list',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'product_cat',
                'field_type' => 'multi_select',
                'allow_null' => 0,
                'add_term' => 0,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'id',
                'multiple' => 0,
            ),
            array(
                'key' => 'field_6297cf29522cd',
                'label' => 'تبلیغ برندها',
                'name' => 'brands_list',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'min'=>1,
                'max'=>7,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6297d0db522ce',
                        'label' => 'تصویر',
                        'name' => 'image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_6297d10b522cf',
                        'label' => 'لینک',
                        'name' => 'link',
                        'type' => 'link',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page',
                    'operator' => '==',
                    'value' => get_option('woocommerce_shop_page_id'),
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_62ac25ed256f7',
        'title' => 'گزینه های برند',
        'fields' => array(
            array(
                'key' => 'field_62ac261813dc7',
                'label' => 'لوگو',
                'name' => 'logo',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_62ac264f13dc8',
                'label' => 'تصویر شاخص',
                'name' => 'thumbnail',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'product_brand',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'field',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_62ac37c406221',
        'title' => 'گزینه های محصول',
        'fields' => array(
            array(
                'key' => 'field_62ac37d8bd495',
                'label' => 'زیر عنوان (‌نام انگلیسی محصول)',
                'name' => 'subtitle',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'product',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_62ac4ffcce021',
        'title' => 'گزینه های صفحه برند',
        'fields' => array(
            array(
                'key' => 'field_62ac501dcc3d5',
                'label' => 'دسته بندی مقالات',
                'name' => 'articles_categories',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'category',
                'field_type' => 'checkbox',
                'add_term' => 1,
                'save_terms' => 0,
                'load_terms' => 0,
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
            ),
            array(
                'key' => 'field_62ac50c7cc3d6',
                'label' => 'تعداد نوشته ها',
                'name' => 'post_count',
                'type' => 'number',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 3,
                'placeholder' => 'تعداد نوشته ها برای نشان دادن',
                'prepend' => '',
                'append' => '',
                'min' => 3,
                'max' => 6,
                'step' => 3,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-brand.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_62ae3ef3f214a',
        'title' => 'گزینه های تماس با ما',
        'fields' => array(
            array(
                'key' => 'field_62ae3efca3421',
                'label' => 'کد فرم تماس',
                'name' => 'contact_form_code',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_62ae3f1ba3422',
                'label' => 'لوکیشن نقشه',
                'name' => 'map_location',
                'type' => 'google_map',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'center_lat' => '',
                'center_lng' => '',
                'zoom' => '',
                'height' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-contact.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;

function product_categyries_field($field)
{
    // Get all taxonomy terms
    $article_types = get_terms(array(
        'taxonomy'   => 'product_cat',
        'hide_empty' => false
    ));

    // Add each term to the choices array.
    // Example: $field['choices']['review'] = Review
    foreach ($article_types as $type) {
        $field['choices'][$type->term_id] = $type->name;
    }

    return $field;
}

add_filter('acf/load_field/name=frontpage_sales_categories', 'product_categyries_field');
add_filter('acf/load_field/name=latest_product_categories', 'product_categyries_field');
add_filter('acf/load_field/name=frontpage_have_discount_categories', 'product_categyries_field');

//add_filter('acf/load_field/name=social_icon', 'mt_social_links');
